### PR TITLE
Use the messagetxt option to make yaya easier to localize

### PR DESCRIPTION
**Pull request by steve02081504**
I didn't write LoadMassageFromTxt because I'm not familiar with the file IO with charset
free to change what I write&thanks

### CODE REVIEW

**Review by steve02081504 — COMMENTED** [review]
reviewed

**Comment by steve02081504** [comment]
I think I forgot @ponapalt .....
草

**Comment by ponapalt** [comment]
I'm tired so I just took a rest.

Note : please fix typo in another PR : massage => message

**Comment by steve02081504** [comment]
Did you mean this?
https://github.com/Taromati2/yaya-shiori/commit/7097a94ece94640a7b33390f2594ca63f374f105
I don't know exactly what Japanese culture is like in this, but in my place, if you are tired, you just need to say to others, "Hey, I'm a little tired. Maybe I'll go on holiday for a week or play games at home for a few days", and they will understand. So I'm a bit confusing when you don't respond for a few days.
And if you have set SSP as a private git repository, maybe I can help.
Of course, if you don't want to, don't force yourself, I can understand

**Comment by ponapalt** [comment]
I've fixed typo.
https://github.com/ponapalt/yaya-shiori/commit/e1d4ad1da794552524b2e7b29a930eebc180cc04

I'm sorry to make you worry. I'll be back to normal after a few more days off.

**Pull request merged**
