### PR TITLE
all fixed

### PR DESCRIPTION
**Pull request by steve02081504**
https://github.com/ponapalt/yaya-shiori/pull/22#issuecomment-877573860

### CODE REVIEW

**Comment by ponapalt** [comment]
Since I can't guarantee that the current directory will not be changed on the SSP (and other runtime software) side, I think you should avoid code that depends on the location of the current directory.
I want to know why you really want to use _wchdir?

**Comment by steve02081504** [comment]
> 
> 
> Since I can't guarantee that the current directory will not be changed on the SSP (and other runtime software) side, I think you should avoid code that depends on the location of the current directory.
> I want to know why you really want to use _wchdir?

Just so that you don't have to change the dictionary
When you move yaya from `ghost/master` to `ghost/master/shiori`, the code for operating files / folders or the basic location of some SAORI calls in dictionaries will be changed to `ghost/master/shiori`, won't it?
If not, I've done something stupid.(XD)

**Comment by steve02081504** [comment]
Now it looks like I did something stupid.
wwwwwwww

**Comment by steve02081504** [comment]
It's all fixed
LoadMessageFromTxt works now
the setting of basepath will only affect the contents other than messagetxt, variable file and yaya.txt

**Pull request merged**
